apiVersion: v1
kind: ReplicationController
metadata: 
 name: myapprc
spec:
 replicas: 1
 selector:
  app: myapprc
  version: 3.3.3
 template:
   metadata:
     labels:
       app: myapprc
       version: 3.3.3
   spec:
    containers:
    - name: rithvikcontainer
      image: nginx
      ports:
      - containerPort: 80

