apiVersion: apps/v1
kind: Deployment
metadata:
 name: rithvikdep
 labels:
  app: rithvik
  version: 1.1.1
spec:
  replicas: 2
  selector: 
   matchLabels:
     app: rithvik
     version: 1.1.1
  template:
    metadata:
      labels:
        app: rithvik
        version: 1.1.1
    spec:
      containers:
      - name: rithvikcon
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
             cpu: 500m
          requests:
             cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: rithvikdep
  labels:
    app: rithvik
spec:
 ports:
 - port: 80
 selector:
   app: rithvik

