apiVersion: v1
kind: ReplicationController
metadata: 
 name: rc
spec:
 replicas: 1
 selector: 
   app: rithvik
   version: 2.2.3
 template:
   metadata:
    labels:
     app: rithvik
     version: 2.2.3
   spec:
      containers:
      - name: rithvikcon
        image: nginx
        ports:
        - containerPort: 8080

