apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels: 
   app: myapp
   version: 5.5.5
spec: 
   type: NodePort
   ports:
   - port: 8080
     nodePort: 30009
     protocol: TCP
   selector: 
     app: myapp
     version: 5.5.5

